dist: trusty
sudo: required
language: c

git:
  submodules: false

install:
 - curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh > install.sh
 - echo | sudo sh install.sh
 - opam init --disable-sandboxing -j 2 --compiler=4.05.0 -n -y
 - eval $(opam env)
 - opam config var root
 - opam repository add coq-released https://coq.inria.fr/opam/released
 - travis_wait opam install coq-elpi.1.3.0 -y

matrix:
  include:

  - env: TEST="test"
    os: linux
    addons:
      apt:
        sources:
        - avsm
    script:
    - eval $(opam env)
    - make
