branches:
  only:
  - master

language:
- nix
- minimal

if: language = minimal
- dist: bionic
- services:
  - docker

env:
- global:
  - NJOBS="2"
  - CONTRIB_NAME="hierarchy-builder"
- matrix:
  - COQ=8.10 ELPI=1.3.0
  - COQ=8.11 ELPI=1.3.1
- matrix:
  - CMD="make && make install"
  - CMD="opam pin add coq-hierarchy-builder . -y -v"

install:
- if: language = minimal
  - ./.travis.docker-install.sh

script:
- if: language = nix
  - nix-build --argstr coq-version "${COQ}"
- if: language = minimal
  - ./.travis.docker-test.sh

after_script:
- if: language = minimal
  - docker stop COQ
